### ISSUE TITLE
declarative openapi validation rules

### ISSUE THREAD

**Issue by clux** [clux/kube-rs#129]
It would be really cool if we had a way to create declarative openapi validation rules ala:
- https://book.kubebuilder.io/reference/generating-crd.html 
- https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#validation

e.g. something like:

```rust
#[derive(OpenapiValidation, Deserialize, Serialize, Clone)]
pub struct FooSpec {
    #[openapi(MinLength=5)
    name: String,
    info: String,
    #[openapi(Minimum=1, Maximum=10)]
    replicas: i32,
}
```

The thing this most reminds me of is serde attributes, but this feels a whole lot dumber than that. We just need to generate: `{ type: object, properties: ... }` from a struct, so it's easy to attach onto the the [crd json!](https://github.com/clux/kube-rs/blob/30762574368f8cb3db30e55e867e5bfa16574ef1/examples/crd_openapi.rs#L59-L80)

The problem with this is that it would necessarily conflict with [serde field attributes](https://serde.rs/field-attrs.html), which are also frequently used. A dumb proc macro that wasn't aware of serde wouldn't be hard to do, but I imagine it also would cause a lot of duplication between between serde attrs like `skip_serializing_if`, `default` with validation rules.

**Comment by clux** [comment]
These look potentially useable:
- https://graham.cool/schemars/
- https://github.com/GREsau/okapi/

via https://old.reddit.com/r/rust/comments/f5m80w/rust_support_for_openapiswagger/

**Comment by clux** [comment]
This could be linked to #159

**Comment by clux** [comment]
Definitely something to do in a proc_macro.

https://book.kubebuilder.io/reference/markers/crd-validation.html has one api set.

**Comment by clux** [comment]
We definitely need something like this to make server side apply useful. The apiserver will default all optionals as null when missing from a yaml patch passed to server side apply otherwise.

**Comment by praveenperera** [comment]
@clux do you think this could be useful: https://docs.rs/rweb/0.5.3/rweb/openapi/index.html

**Comment by clux** [comment]
That looks promising. Seems the related proc-macro module is here: https://github.com/kdy1/rweb/tree/master/macros/src/openapi . From a quick glance it also seems tied to a web framework for customizability, and can't tell if it's openapi v2 or v3. But that said, `#[derive(Schema)]` would be very nice.

**Comment by praveenperera** [comment]
@clux cool i’m going to look at that more if I get a chance Tomorrow. 

I’m relatively new to rust, and haven’t worked with proc macros before. Any idea how hard it might be to copy those files over and make it work for our needs?

**Comment by clux** [comment]
If you're willing to try it out and see if the schema it produces is usable and can be put onto the newly required `schemas` property, then that certainly would be valuable. Experimentation on that front would be very appreciated.

That said, I know that proc-macros are definitely not an easy entry-point into rust. It's meta code that generates real code (frequently inside other macros like `quote!`) so it can be a bit confusing to read if you're not already familiar with rust's syntax. But if you feel that you can read and understand it, go for it!

The proc-macro crate we have in this repo is `kube-derive` which you can try it out with `cargo run --examples crd_derive`  and with `cargo-expand` you can see what code it generates. Might be a decent starting point to see how it works.

**Comment by praveenperera** [comment]
I've done some experimenting and I've learned it is the OpenAPI v3 spec.

Here is what I got:

**Hand written**
```yaml
            spec:
              description: "Issuer"
              type: object
              required:
                - domainName
                - dnsProvider
              properties:
                domainName:
                  type: string
                provider:
                  type: string
                  enum: [cloudflare, digitalocean]
                key:
                  type: string
                secretKey:
                  type: string
```

**Generated**
```
    let schema = <CertIssuerSpec as Entity>::describe();
    println!("SCHEMA: \n{}\n", serde_yaml::to_string(&schema)?);
```

```yaml
type: object
properties:
  domainName:
    type: string
  dnsProvider:
    type: object
    properties:
      provider:
        enum:
          - DigitalOcean
          - Cloudflare
      key:
        type: string
      secretKey:
        type: string
  secretName:
    type: string
    nullable: true
  namespaces:
    type: array
    items:
      type: string
```

**Comment by clux** [comment]
Hey this is really promising!  Sounds like this is potentially possible to port into `kube-derive` in a modified form. Thanks a lot for looking into this.

Some quick comments on the problems for now:

1. it is possible to act an struct-level serde attrs so we can parse `#[serde(rename_all = ...)]` (i think)
2. enums might be a pain point we have to caveat anyway given that we can do fancy genrealized enums, and go cannot. But not sure what good defaults are atm (did not find any enum docs on the [crd page](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/))
3. This is probably something we can also generate from the struct by doing a loop over all the fields and looking for nullable equivalent things like Option (or things that have serde(default)
4. `description` might need a special attr if we even care for it (looks like it can apply to both fields and the main spec struct?)

**Comment by praveenperera** [comment]
>  proc-macro crate defining #[openapi] attrs and invoking that from kube-derive

I think this would be a great approach 

> 3. This is probably something we can also generate from the struct by doing a loop over all the fields and looking for nullable equivalent things like Option (or things that have serde(default))

I he is doing something like this for the `ResponseEntity` but I guess he just didn't do it for schema?
https://github.com/kdy1/rweb/blob/master/src/openapi/mod.rs#L287

> description might need a special attr if we even care for it (looks like it can apply to both fields and the main spec struct?) - probably fine to ignore in the first PoC

Agreed! Definitely not needed for POC

**Comment by clux** [comment]
Yeah, it looks like there's tons of things the proc macro could fill in by looking at the root [Schema definition](https://github.com/kdy1/openapi/blob/master/src/v3_0/schema.rs). (At least that's the crate rweb uses, seems to be a soft fork of https://github.com/softprops/openapi - probably because of https://github.com/softprops/openapi/issues/22)

**Comment by praveenperera** [comment]
Hey a heads up, Kubernetes has some extra rules which means some valid OpenAPIV3 schemas are actually invalid in K8s world. It has to do with structural schemas: https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#specifying-a-structural-schema

Example: 

Rust: 

```rust
#[derive(Serialize, Deserialize, Clone, Debug, Schema)]
#[serde(tag = "provider")]
#[serde(rename_all = "lowercase")]
pub enum DnsProvider {
    DigitalOcean(BasicAuth),
    Cloudflare(BasicAuth),
    Route53(Route53),
}

#[derive(Serialize, Deserialize, Clone, Debug, Schema)]
#[serde(rename_all = "camelCase")]
pub struct BasicAuth {
    key: String,
    secret_key: String,
}

#[derive(Serialize, Deserialize, Clone, Debug, Schema)]
#[serde(rename_all = "camelCase")]
pub struct Route53 {
    access_key: String,
    secret_access_key: String,
    region: String,
    profile: Option<String>,
    hosted_zone_id: Option<String>,
}
```

rweb produces this, but it is invalid as a structural schema:

```yaml
type: object
properties:
  domainName:
    type: string
  dnsProvider:
    oneOf:
      - type: object
        properties:
          key:
            type: string
          secretKey:
            type: string
      - type: object
        properties:
          key:
            type: string
          secretKey:
            type: string
      - type: object
        properties:
          accessKey:
            type: string
          secretAccessKey:
            type: string
          region:
            type: string
          profile:
            type: string
            nullable: true
          hostedZoneId:
            type: string
            nullable: true
  secretName:
    type: string
    nullable: true
  namespaces:
    type: array
    items:
      type: string
```

Instead it would have to be written something like this:

```yaml
                dnsProvider:
                  type: object
                  required: ["provider"]
                  properties:
                    provider:
                      type: string
                      enum: ["digitalocean"]
                    key: { "type": "string" }
                    secretKey: { "type": "string" }
                    accessKey: { "type": "string" }
                    secretAccessKey: { "type": "string" }
                    region: { "type": "string" }
                    hostedZoneId: { "type": "string" }
                  oneOf:
                    - properties:
                        provider:
                          enum: ["digitalocean"]
                      required: ["provider", "key", "secretKey"]
                    - properties:
                        provider:
                          enum: ["cloudflare"]
                      required: ["provider", "key", "secretKey"]
                    - properties:
                        provider:
                          enum: ["route53"]
                      required: ["accessKey", "secretAccessKey", "region"
```
