### ISSUE TITLE
APIClient uses system:anonymous service account when running code locally 

### ISSUE THREAD

**Issue by thavlik** [clux/kube-rs#196]
```
#[cfg(test)]
mod test {
    use k8s_openapi::api::apps::v1beta1::{DeploymentSpec, DeploymentStatus};
    use k8s_openapi::api::core::v1::Pod;
    use kube::{
        api::{Api, DeleteParams, Object},
        client::APIClient,
        config::{self, ConfigOptions, Configuration},
    };
    
    #[tokio::test]
    async fn test_general() {
        let config = config::load_kube_config_with(ConfigOptions{
            context: Some(String::from("do-nyc1-dev")),
            cluster: Some(String::from("do-nyc1-dev")),
            user: Some(String::from("do-nyc1-dev-admin")),
        }).await.unwrap();
        let client = APIClient::new(config);

        let pods: Api<Pod> = Api::namespaced(client, "default");

        let p = pods.get("blog").await.unwrap();
        println!(
            "Got blog pod with containers: {:?}",
            p.spec.unwrap().containers
        );
    }
}
```

```
KUBECONFIG=$HOME/.kube/config cargo test
---- test::test_general stdout ----
thread 'test::test_general' panicked at 'called `Result::unwrap()` on an `Err` value: Api(ErrorResponse { status: "Failure", message: "pods \"blog\" is forbidden: User \"system:anonymous\" cannot get resource \"pods\" in API group \"\" in the namespace \"default\"", reason: "Forbidden", code: 403 })', src/main.rs:75:17
```

For reference, here is the ExecCredentials command from my kubeconfig:
```
- name: <my-cluster-name>
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - kubernetes
      - cluster
      - kubeconfig
      - exec-credential
      - --version=v1beta1
      - --context=default
      - <uuid>
      command: doctl
      env: null
```
