### ISSUE TITLE
Reconcile not called if the CR is Cluster scoped and the `owns` children are namespaced

### ISSUE THREAD

**Issue by praveenperera** [clux/kube-rs#293]
Example: My custom resource `CertIssuer` is not scoped to a namespace. The CRD for is `scope: Cluster`.

I want my controller to be able to manage certificates across the cluster. Across many different namespaces.

Its children are `Secrets`. But Secrets have to be scoped to a namespace.

In this case the children (Secrets) would never trigger the reconcile function. Right?

Maybe a solution is if the `selector` field was public. I could make my own version of `owns` using `trigger_with`.

Or for a situation like this should I just be using `watchers` directly instead of using `controller`?

**Comment by clux** [comment]
if you've hooked up:

```rust
let certs = Api<CertIssuer>::all();
let secrets = Api<Secret>::all();
Controller::new(certs, lp).owns(secrets, lp)
```

then reconcile should get triggered on all secrets (maybe you wanna scope secret listparams to some selector).
If  you said `Api::namespaced(ns)` for `Api<Secret>` then you're bound to only one namespace.

**Comment by praveenperera** [comment]
Hey I think I could have explained this better. 

This is exactly how I have it set up. However, even this way, the reconcile is never triggered if I change any of the secrets. 

```rust
let certs = Api<CertIssuer>::all();
let secrets = Api<Secret>::all();
Controller::new(certs, lp).owns(secrets, lp)
```

I think I know the reason why. 

My CertIssuer is clustered scoped custom resource so the, so it doesn't have a namespace in metadata. It looks like this:

```yaml
apiVersion: certmaster.kuberails.com/v1
kind: CertIssuer
metadata:
  name: com-ok-kuberails
spec:
  domainName: praveenperera.com
  namespaces:
    - default
    - praveen
  dnsProvider:
    provider: cloudflare
    key: thisIsMyKey
    secretKey: thisIsMySecretKey
```

However all secrets are namespaced.

https://github.com/clux/kube-rs/blob/master/kube-runtime/src/controller.rs#L85-L92

Here it looks like it uses the namespace of the owner to find the children? But the namespace of the owner is always `None` and all the children with have `Some(namespace)`
