### ISSUE TITLE
Silent error getting kube config in-cluster

### ISSUE THREAD

**Issue by benjamin-wright** [clux/kube-rs#331]
Hi, I'm having a really basic problem with getting `kube` working in cluster with my k3s cluster (v1.18.9-k3s1). I have a very simple application which is basically just the following:

```rust
#![feature(proc_macro_hygiene, decl_macro)]

extern crate kube;
extern crate serde;
extern crate serde_json;

use kube::{ Config };

#[tokio::main]
async fn main() -> Result<(), kube::Error> {
    println!("Starting...");

    println!("Getting kube config...");
    let config_result = Config::from_cluster_env(); //This is breaking

    println!("Resolving kube config result...");
    let config = match config_result {
        Ok(config) => config,
        Err(e) => {
            println!("Error getting config {:?}", e);
            return Err(e);
        }
    };

    println!("Finished!");
    Ok(())
}
```

```toml
[dependencies]
kube = { version = "0.43.0", default-features = false, features = ["derive", "native-tls"] }
kube-runtime = { version = "0.43.0", default-features = false, features = [ "native-tls" ] }
k8s-openapi = { version = "0.9.0", default-features = false, features = ["v1_18"] }
serde =  { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
serde_json = "1.0"
tokio = { version = "0.2.22", features = ["full"] }
reqwest = { version = "0.10.8", default-features = false, features = ["json", "gzip", "stream", "native-tls"] }
```

The output I'm getting is:

```
[server] Starting...
[server] Getting kube config...
[K8s EVENT: Pod auth-controller-6fb8f87b4d-5stf5 (ns: ponglehub)] Back-off restarting failed container
```

I'm hoping this is something obvious in my dependencies, but am suspicious that it's a K3S compatibility issue, since I tried using `rustls` originally and had to switch to native openssl because the k3s in-cluster api server address is an IP address rather than a hostname...

**Comment by clux** [comment]
It's not a lot the `Config::from_cluster_env` fn is doing other than reading environment variable.
My first thought is that you might not be have `automountServiceAccountToken: true` to get the evars in there.

Weird that you are not getting Error information from the call. It should return an Error (and clearly it's crashing).

dependency wise, if you are not using rustls, you can take out the `default-features = false` on kube and kube-runtime and just pick the features you want (like derive for kube)

**Comment by benjamin-wright** [comment]
Hi @clux, thanks for getting back to me so quickly. Sorry, the output is from Tilt, which I'm using to deploy and pipe back the logs. But `k9s` gives a similar story:

```
Starting...           
Getting kube config...
stream closed         
```

Yeah, it's the lack of logs that's really getting me. I haven't created an explicit service account for it yet, will try giving it a service account and see if that was throwing it for a loop somehow. Ta for the pointer on default-features :)

**Comment by benjamin-wright** [comment]
Nope, explicit serviceaccount with explicit `automountServiceAccountToken: true`, same output 😞

**Comment by clux** [comment]
are you associating the deployment with the service account?
https://github.com/clux/kube-rs/blob/master/tests/deployment.yaml#L114

**Comment by benjamin-wright** [comment]
Yup:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: auth-controller
    app.kubernetes.io/managed-by: tilt
  name: auth-controller
  namespace: ponglehub
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: auth-controller
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: auth-controller
        app.kubernetes.io/managed-by: tilt
        tilt.dev/pod-template-hash: ad41af2b3e7eaa93efd5
    spec:
      containers:
      - image: auth-controller:tilt-20f9932817b95f85
        imagePullPolicy: IfNotPresent
        name: server
        resources:
          limits:
            cpu: 100m
            memory: 32Mi
          requests:
            cpu: 100m
            memory: 32Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: auth-controller
      serviceAccountName: auth-controller
      terminationGracePeriodSeconds: 30
```
