### ISSUE TITLE
Use `doc_cfg` (`#[doc(cfg(feature = "..."))]`) to show feature requirements

### ISSUE THREAD

**Issue by kazk** [clux/kube-rs#365]
Show these in docs for `derive` and `ws`:
![image](https://user-images.githubusercontent.com/639336/103467745-f45fe580-4d06-11eb-906f-0110689cf618.png)

`![feature(doc_cfg)]` is nightly only, but `docs.rs` uses nightly by default.

From https://stackoverflow.com/a/61417700

```toml
# docs.rs-specific configuration
[package.metadata.docs.rs]
# document all features
all-features = true
# defines the configuration attribute `docsrs`
rustdoc-args = ["--cfg", "docsrs"]
```
```rust
// only enables the `doc_cfg` feature when
// the `docsrs` configuration attribute is defined
#[cfg_attr(docsrs, feature(doc_cfg))]

#[cfg_attr(docsrs, doc(cfg(feature = "macros")))]
pub fn test() {}
```
