### ISSUE TITLE
Generated CRD object uses inflected plural form over explicitly specified

### ISSUE THREAD

**Issue by teozkr** [clux/kube-rs#480]
Reported [on Discord](https://discord.com/channels/500028886025895936/685161813675212899/825764045859979308) by @pscheidl

Basically, this `struct`:

```rust
#[derive(CustomResource, Serialize, Deserialize, Debug, PartialEq, Clone, JsonSchema)]
#[kube(
    group = "pavel.cool",
    version = "v1",
    kind = "Echo",
    shortname = "echo",
    plural = "echoes",
    derive = "PartialEq"
)]
struct EchoSpec {
    replicas: i32,
}
```

Generates this (abridged) CRD:

```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: echos.pavel.cool
spec:
  group: pavel.cool
  names:
    kind: Echo
    plural: echos
    singular: echo
    shortNames:
      - echo
```

When it should be:

```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: echoes.pavel.cool
spec:
  group: pavel.cool
  names:
    kind: Echo
    plural: echoes
    singular: echo
    shortNames:
      - echo
```

**Comment by clux** [comment]
I believe extending our `Resource` trait with the `plural` and having `kube-derive` implement `kube::Resource` directly, rather than `k8s_openapi::Resource` will fix this.

That is what #468 wants to do, but it got a little sidelined by the big Resource/Meta restructurings. I'll see if I can get that moving again.

**Comment by clux** [comment]
Although, looking at the code, I'm a bit confused of why this is happening as is. The `metadata.name` is generated from the plural:

```
    let crd_meta_name = format!("{}.{}", plural, group);
    let crd_meta = quote! { { "name": #crd_meta_name } };
```

**Comment by clux** [comment]
Yeah, setting `#[kube(plural = "echoes")]` totally does work.

The abridged output of your example is actually:

```
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: echoes.pavel.cool
spec:
  group: pavel.cool
  names:
    kind: Echo
    plural: echoes
    shortNames:
      - echo
    singular: echo
  scope: Cluster
```

So this is slightly invalid. The point that Pavel brings up is that while the CRD is correct, the url generation does not use that, because that information is not contained in our Meta/Resource trait.
