### ISSUE TITLE
Missing apiVersion, Kind and metadata properties in schemas of generated crd

### ISSUE THREAD

**Issue by 12101111** [clux/kube-rs#546]
In kube-derive, the generated crd don't contain schema of `apiVersion`, `Kind` and `metadata` properties. Is this intended? 
```rust
    #[doc = #docstr]
    #[derive(#(#derive_paths),*)]
    #[serde(rename_all = "camelCase")]
    #visibility struct #rootident {
        #schemars_skip
        #visibility api_version: String,
        #schemars_skip
        #visibility kind: String,
        #schemars_skip
        #visibility metadata: k8s_openapi::apimachinery::pkg::apis::meta::v1::ObjectMeta,
        #visibility spec: #ident,
        #statusq
    }
```

The crd generated from code-generator contains those properties:

```yaml
    openAPIV3Schema:
      properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
        spec:
...
```
