### ISSUE TITLE
kube-derive: yaml vs. rust question

### ISSUE THREAD

**Issue by webern** [clux/kube-rs#553]
Is the correct workflow to maintain a CRD spec both as a YAML file and as a Rust struct with the CustomResource derive? Or can the YAML be generated from the Rust struct (or the Rust struct from the YAML)? Or can the CRD be applied to the cluster by a Rust program that skips the YAML formatting altogether?

Thanks. I'm just getting started. I hope the question is clear. I'm trying to understand the developer workflow for keeping

```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mycrd
```

in sync with

```rust
#[derive(CustomResource, Serialize, Deserialize, Debug, PartialEq, Clone, JsonSchema)]
#[kube(
    group = "example.com",
    version = "v1",
    kind = "MyCrd",
    plural = "mycrds",
    derive = "PartialEq",
    namespaced
)]
#[kube(status = "MyCrdStatus")]
pub struct MyCrdSpec {
  // ...
}
```
